language: python
python:
  - "3.7"
  - "3.8"
install:
  - gem install chef-utils -v 16.6.14
  - gem install mdl
  - pip install -r requirements_dev.txt
  - pip install -e .
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make check
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
